### ISSUE TITLE
Nostrmo client

### ISSUE THREAD

**Issue by jawsh207** [haorendashu/nostrmo_faq#1]
Is the Nostrmo client open source? I'm able to find the faq here but doesn't seen to be any client builds on GitHub. If it is open source I'd like to test and maybe add to nostrlink.net
Assuming it can also be ran without Google apps/services.

**Comment by shaibearary** [comment]
chatted with author before he said it will be open source soon

**Comment by haorendashu** [comment]
Hello, this client has open source at https://github.com/haorendashu/nostrmo
Thanks.
